name: Generate Dev Container Images
on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write
jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Rust
        run: |
          set -e

          # [Optional] Enable buildkit, set output to plain text for logging
          export DOCKER_BUILDKIT=1
          export BUILDKIT_PROGRESS=plain

          # Login to GitHub Container Registry
          echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

          # Rust container
          IMAGE_NAME="rust:dev"
          IMAGE_REPOSITORY="$(echo "ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')"
          cd rust && docker build . -t "${IMAGE_REPOSITORY}" && docker push "${IMAGE_REPOSITORY}" && cd ..

          # TypeScript container
          IMAGE_NAME="typescript:dev"
          IMAGE_REPOSITORY="$(echo "ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')"
          cd typescript && docker build . -t "${IMAGE_REPOSITORY}" && docker push "${IMAGE_REPOSITORY}" && cd ..

